# Generated by Django 4.1.4 on 2023-01-03 08:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'سبد ها',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('created', models.DateField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name_plural': 'مجموعه ها',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('created', models.DateField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('first_name', models.CharField(max_length=25, verbose_name='نام')),
                ('last_name', models.CharField(max_length=25, verbose_name='نام خوانوادگی')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='لطفا شماره همراه خود را وارد کنید', max_length=128, region=None, unique=True, verbose_name='شماره همراه')),
                ('birthday', models.DateField(default=datetime.datetime.now, verbose_name='تاریخ تولد')),
                ('membership', models.CharField(choices=[('برنز', 'عضویت برنزی'), ('نقره', 'عضویت نقره ای'), ('طلا', 'عضویت طلای')], default='برنز', max_length=5, verbose_name='نوع عضویت')),
            ],
            options={
                'verbose_name_plural': 'مشتریان',
                'ordering': ['birthday'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('placed_at', models.DateField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('payment_status', models.CharField(choices=[('در انتظار', 'در انتظار پرداخت'), ('تکیمل', 'پرداخت تکمیل شده است'), ('لغو عملیات', 'لغو عملیات پرداخت')], default='در انتظار', max_length=15, verbose_name='وضعیت پرداخت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_item', to='store.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name_plural': 'وضعیت سفارش',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('created', models.DateField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('discount', models.FloatField(verbose_name='تخفیف')),
            ],
            options={
                'verbose_name_plural': 'تبلیغات',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.customer', verbose_name='مشتری')),
                ('created', models.DateField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('city', models.CharField(max_length=25, verbose_name='شهر')),
                ('street', models.TextField(max_length=200, verbose_name='خیابان')),
            ],
            options={
                'verbose_name_plural': 'ادرس مشتریان',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('created', models.DateField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateField(auto_now=True, verbose_name='به روز رسانی شده')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیاحات')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='نامک')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='قیمت واحد')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_item', to='store.collection', verbose_name='مجموعه')),
                ('promotion', models.ManyToManyField(related_name='promotion_item', to='store.promotion', verbose_name='تبلیغات')),
            ],
            options={
                'verbose_name_plural': 'محصولات',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('created', models.DateField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('quantity', models.SmallIntegerField(verbose_name='تعداد')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='قیمت واحد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='store.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_items', to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='featured_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_item', to='store.product', verbose_name='محصول ویژه'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('created', models.DateField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('quantity', models.SmallIntegerField(verbose_name='تعداد')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='store.cart', verbose_name='سبد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name_plural': 'سبد خرید',
                'ordering': ['-created'],
            },
        ),
    ]
