# Generated by Django 4.1.4 on 2022-12-31 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_address_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created'], 'verbose_name_plural': 'ادرس مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created'], 'verbose_name_plural': 'سبد ها'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created'], 'verbose_name_plural': 'سبد خرید'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-created'], 'verbose_name_plural': 'مجموعه ها'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['birthday'], 'verbose_name_plural': 'مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-placed_at'], 'verbose_name_plural': 'وضعیت سفارش'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created'], 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated'], 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name_plural': 'تبلیغات'},
        ),
    ]
