# Generated by Django 4.1.6 on 2023-02-18 09:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='لطفا شماره همراه خود را وارد کنید', max_length=128, null=True, region=None, unique=True, verbose_name='شماره همراه'),
        ),
    ]
