# Generated by Django 4.1.6 on 2023-03-06 15:08

from django.db import migrations, models
import store.validator


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_image_productimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(upload_to='store/product', validators=[store.validator.validate_image_file]),
        ),
    ]
