# Generated by Django 4.1.4 on 2023-01-05 20:53

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_orderitem_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='IRR', max_digits=50, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='IRR', max_digits=50, verbose_name='قیمت واحد'),
        ),
    ]
