# Generated by Django 4.1.4 on 2023-01-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_cartitem_options_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Cart',
        ),
    ]
