# Generated by Django 4.1.4 on 2023-01-17 19:10

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='IRR', max_digits=50, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='به روز رسانی شده'),
        ),
    ]
