# Generated by Django 4.1.4 on 2023-01-18 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_price_alter_product_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('created', models.DateField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('name', models.CharField(max_length=255, verbose_name='نام کاربر')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
    ]
