# Generated by Django 4.1.4 on 2023-01-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
