# Generated by Django 4.1.4 on 2023-01-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['label'], 'verbose_name': 'برچسبی', 'verbose_name_plural': ' برچسب ها'},
        ),
        migrations.AlterModelOptions(
            name='tagitem',
            options={'verbose_name': 'برچسب های انتخابی', 'verbose_name_plural': 'برچسب انتخابی توسط کاربر'},
        ),
    ]
