# Generated by Django 4.1.6 on 2023-02-18 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='نام کاربری باید بین 6 تا 30 کاراکتر باشد و فقط حروف کوچک و بزرگ لاتین مجاز است', regex='^[a-zA-Z]{6,30}$')], verbose_name='نام کاربری'),
        ),
    ]
