# Generated by Django 4.1.6 on 2023-02-18 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='فقط حروف فارسی مجاز است', regex='[\\u0600-\\u06FF]$')], verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='فقط حروف فارسی مجاز است', regex='[\\u0600-\\u06FF]$')], verbose_name='نام خانوادگی'),
        ),
    ]
